### ISSUE TITLE
How to find the dataset in Paper Real-World Image Datasets for Federated Learning?

### ISSUE THREAD

**Issue by SoleilLim** [FederatedAI/research#11]
When I open the link you have mentioned in ReadME, which is https://https://fate.fedai.org, I just find a website of a project. However, I didn't find the dataset. And I think the dataset is vary important for me to do some experiments. So can you tell me how to find it at your convience? Thanks!

**Comment by yankang18** [comment]
Please send an email to contact@fedai.org for requesting the dataset. Note that you are required to use an email ending with .edu.

**Comment by yankang18** [comment]
problem solved
