### ISSUE TITLE
 Issue with Federated Learning Model Evaluation

### ISSUE THREAD

**Issue by AIXZHAO** [FederatedAI/research#12]
I am running the code given by paper “Real-World Image Datasets for Federated Learning”, where multiple clients participate in model training and evaluation. During the model evaluation phase, I am encountering an issue where only the client with ID 1 is able to respond to the server's model evaluation command, while the other clients fail to execute the model evaluation code.

Upon debugging, I have confirmed that the server is sending the evaluation command to all clients, and the client with ID 1 is correctly executing the evaluation code. However, the other clients do not execute the evaluation code and no error message is generated.

I am unsure of the specific cause of the issue, as there does not appear to be any network connectivity or client configuration issues. When I changed the code to run with only one client, the code was able to execute successfully.

I would appreciate any guidance on how to identify the cause of this issue and possible areas to investigate for a solution

**Comment by AIXZHAO** [comment]
Problem has been solved.Use websockets instead of gevent or eventlet.

**Comment by yankang18** [comment]
problem solved
