### ISSUE TITLE
Is DLG attack implemented in fedcg project code?

### ISSUE THREAD

**Issue by FryLcm** [FederatedAI/research#15]

**Comment by FryLcm** [comment]
I didn't find the dlg attack part and the psnr calculation part in the project.

**Comment by yankang18** [comment]
https://github.com/yankang18/FedCG/tree/main

**Comment by yankang18** [comment]
check the code at https://github.com/yankang18/FedCG/tree/main

**Comment by yankang18** [comment]
issue addressed
