### ISSUE TITLE
How to download the Street dataset mentioned in the paper "Real-World Image Datasets for Federated Learning"?

### ISSUE THREAD

**Issue by flying-pigeon** [FederatedAI/research#8]
When I'm looking for the Street dataset via the link offered in the paper, which is https://dataset.fedai.org/, I find nothing related to Street dataset but an advertisement concerning WeBank. I suspect that the website downloading dataset has been modified. Therefore, how can I get access to the Street dataset? Help me  plz.

**Comment by yankang18** [comment]
Sorry for the delay:
               You can send an email to contact@fedai.org to request the dataset. Please note that we only distribute the dataset to educational institutes. Therefore, you must request the data with an email with .edu as the domain name.
