### ISSUE TITLE
 Where is the Street dataset mentioned in the paper "Real-World Image Datasets for Federated Learning"?

### ISSUE THREAD

**Issue by SuperXxts** [FederatedAI/research#9]
I can't find the dataset used by "Real-World Image Datasets for Federated Learning" through the link given.

**Comment by yankang18** [comment]
Sorry for the delay:
               You can send an email to contact@fedai.org to request the dataset. Please note that we only distribute the dataset to educational institutes. Therefore, you must request the data with an email with .edu as the domain name.
